### ISSUE TITLE
Move code from https://github.com/maximilien/homebrew-kn-plugins

### ISSUE THREAD

**Issue by maximilien** [knative-sandbox/homebrew-kn-plugins#1]
Move initial code from https://github.com/maximilien/homebrew-kn-plugins to this repo

**Comment by maximilien** [comment]
Done, see commit: ef33e0f82f9dbc17d638b7445905994d84f2ebdf

However, we have both `master` and `main` branches (same content) and I don't have authority to switch default to `main` since my view of the repo on Github does not have "Settings" tab enabled. 

Perhaps @rhuss  or @markusthoemmes can switch it or authorize me?

cc: @navidshaikh

**Comment by markusthoemmes** [comment]
Deleted the existing `main` and renamed `master` to `main`, which is now the default.

**Comment by maximilien** [comment]
Thanks @markusthoemmes
