### ISSUE TITLE
Quickstart plugin not findable by `kn`

### ISSUE THREAD

**Issue by psschwei** [knative-sandbox/homebrew-kn-plugins#23]
In an earlier [Slack discussion](https://knative.slack.com/archives/CE4MVFVAQ/p1626964104136700), we noted that as is, the `quickstart` plugin is not found by the `kn` client when installed via Brew. 

There were two potential solutions mentioned:
1. Install the plugin to `~/.config/kn/plugins`
2. Default `kn` to look up from PATH as well

**Comment by csantanapr** [comment]
I'm confused about this because this repo already has plugins being install with brew like `admin` and `source-kafka` then how are people using this plugin being install in `PATH` if `kn` is unable to find them @rhuss

**Comment by maximilien** [comment]
`kn` has two methods for finding plugins: `PATH` and `~.config/kn/plugins`. You can specify which you want with a [`config.yml`](https://github.com/knative/client/tree/main/docs#options) or everytime you call `kn` (suboptimal)

**Comment by maximilien** [comment]
See issues #8 and #9
