### ISSUE TITLE
Update to version 1.0.1

### ISSUE THREAD

**Issue by ssdowd** [knative-sandbox/homebrew-kn-plugins#50]
kn-plugin-quickstart version 1.0.1 added native m1/arm support.

**Comment by csantanapr** [comment]
We only release minor releases in homebrew, you need to get binary for patch directly from git repo release.

We are currently working on releasing v1.1 and m1/arm will be included

**Comment by csantanapr** [comment]
v1.1 is now released https://github.com/knative-sandbox/homebrew-kn-plugins/pull/55

/close
