### ISSUE TITLE
Integrate into the knative-client release train via some automated process

### ISSUE THREAD

**Issue by maximilien** [knative-sandbox/homebrew-kn-plugins#6]
Similar to [issue 18](https://github.com/knative/homebrew-client/issues/18) of homebrew-client

The formulas should be updated (semi-) automatically when a new kn release is performed.

This can be done in several ways:

* Create a script here that goes over to the client release pages and syncs the scripts. This can be called ad-hoc after a release or maybe even periodically via a GitHub action
* Add the creation of a PR to the release.sh script when doing the client release, so make the creation of the scripts a part of the client release process.

Well the second options might be nicer, the first one is easier.

**Comment by psschwei** [comment]
Given that there's a good chance I'll be on the hook for this in the 1.6 release, may as well take a stab at this... July Paul thanks me in advance :smiley: 
/assign

**Comment by psschwei** [comment]
This was fixed by #94 (or would've been if I could spell "Fixs" ;) )
